buyer/urls.py
from django.urls import path
from buyer import views

app_name = 'buyer'

urlpatterns=[
    # path('buyerapp/',views.buyerapp,name='buyerapp'),
    path('',views.buyerapp,name='buyerapp'),
    path('proddetails/<int:id>/',views.proddetails,name ='proddetails'),
    path('cartitems/',views.cartitems,name='cartitems'),
    path('removecart/<int:id>/',views.removecart,name='removecart'),
    path('buyitems/<int:id>/',views.buyitems,name='buyitems'),
    path('addDeliveryDetails/<int:id>/',views.addDeliveryDetails,name='addDeliveryDetails'),
    path('history/',views.history,name='history'),
    path('order/',views.order,name='order'),
    path('notification/',views.notification,name='notification'),
    path('buyerprofile/',views.buyerprofile,name='buyerprofile'),
    path('addressform/',views.addAddress,name='addAddress'),
    path('checkout/<int:id>/',views.checkout,name='checkout'),
    path('buyallproduct/',views.buyallproduct,name='buyallproduct'),
    path('checkoutallprod/',views.checkoutallprod,name='checkoutallprod'),

    path('search/',views.searchView,name='search'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.homepage),
    path('register/',views.register,name='register'),
    path('login_call/',views.login_call,name='login'),
    path('logout_call/',views.logout_call,name='logout'),
    # path('buyer/',include("buyer.urls")),
    path('',include("buyer.urls")),
    path('seller/',include("seller.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from seller import views

app_name = 'seller'

urlpatterns=[
    path('sellerapp/',views.sellerapp),
    path('addproduct/',views.addproduct),
    path('addcategory/',views.addcategory),
    path('addedproduct/',views.addedproduct),
    path('modifyproduct/<int:id>/',views.modifyproduct,name='modifyproduct'),
    path('sellernotifications/',views.sellernotifications),
    path('createnotifications/',views.createnotifications),
    path('sellerorders/',views.sellerorders),
    path('sellershippcall/<int:id>',views.sellershippcall,name = 'sellershippcall'),
]

templates/addedproduct.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}
<br>
<div class="row">
	{% for i in prod %}
	<br>
	<div class="col-md-4 card" style="width: 18rem;">
	  <img class="card-img-top" src="{{ i.product_img.url }}" alt="product img!">
	  <div class="card-body">
	    <h5 class="card-title">{{ i.product_name }}</h5>
	    <p class="card-text">Rs {{ i.product_price }}/-</p>
	    <a href="{% url 'seller:modifyproduct' id=i.id %}" class="btn btn-primary">Modify</a>
	  </div>
	</div>
	<br>
	{% endfor %}
</div>
<br>
{% endblock %}

templates/addproduct.html
{% extends 'base.html' %}


{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}

	<br><br>
	<h1>Add Product</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label>Product Name: </label><input type="text" name="pname" class="form-control"><br>

		<label>Description: </label><input type="text" name="desc" class="form-control"><br>

		<label>Price: </label><input type="number" name="price" class="form-control" class="form-control"><br>

		<label>Image: </label><input type="file" name="fil"><br><br>

		<label>Quantity: </label><input type="number" name="qty" class="form-control"><br>

		<label for="">Category:</label><br>
		<select name="catid" class="form-control">
		{% for i in lis %}
			<option value="{{i.cat}}">{{i.cat}}</option>
		{% endfor %}
		</select><br>

		<!--<input type="hidden" name="uname" value="{{request.user}}">-->

		<label>Save Date: </label><br><input type="text" name="sav"><br>

		<label>modified Date: </label><br><input type="text" name="mod"><br>

		<br><input type="submit" value="Add Product" class="btn-primary"><br>

	</form>
	<br><br>
{% endblock %}

templates/addressform.html
{% extends 'base.html' %}

{% block mainblock %}

<!-- uaddid = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
houseno = models.CharField(max_length=20)
    street = models.CharField(max_length = 100)
    ward = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    pin = models.CharField(max_length=6)
    state = models.CharField(max_length=50) -->


<style>
  #id_houseno{
    color: red;
    width: 100px;
    border-radius: 5px;
    border: 1px solid orange;
  }
</style>

<div class="w3-container w3-padding">
  <!-- Start of Checkout Wrapper -->
  <div class="checkout-wrapper pt-10 pb-70">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <main id="primary" class="site-main">
                    <div class="checkout-area">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-6 col-lg-7">
                                <div class="checkout-form">
                                    <div class="section-title left-aligned">
                                        <h3>Billing Details</h3>
                                    </div>

                                   

                                    <form action="{% url 'buyer:addAddress' %}"  method="post" enctype="multipart/form-data">
                                    {% csrf_token %}

                                    <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-12">
                                          <label for="p_address">Address <span class="text-danger">*</span></label>
                                          <input name="houseno" type="text" class="form-control" id="p_address" required>
                                      </div>
                                  </div>
                                  <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="city_name">City <span class="text-danger">*</span></label>
                                          <input name="city" type="text" class="form-control" id="city_name" required>
                                      </div>
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="province_name">Colony <span class="text-danger">*</span></label>
                                          <input type="text" class="form-control" name="state" id="province_name" required>
                                      </div>
                                  </div>
                                  <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="zip_code">Zip Code <span class="text-danger">*</span></label>
                                          <input type="number" class="form-control" name="pin" id="zip_code" required>
                                      </div>
                                   
                                  </div>
                        

                                    
                                        <input type="hidden" name='red' value="{{red}}">
                                        <input type="submit" class="btn btn-secondary dark" value="Save">
                                    </form>           
                                     
                                  </div>

                                            

                                           
                              
                                </div> <!-- end of checkout-form -->
                            </div>
                          
                        </div> <!-- end of row -->
                    </div> <!-- end of checkout-area -->
                </main> <!-- end of #primary -->
            </div>
        </div> <!-- end of row -->
    </div> <!-- end of container -->

</div>
<!-- End of Checkout Wrapper -->



      




</div>
<br>
{% endblock %}


<!--
  <input type="text" name="hno" value="" placeholder="House no." required>
  <input type="text" name="street" value="" placeholder="Street" required>
  <input type="text" name="ward" value="" placeholder="Ward"  required>
  <input type="text" name="city" value="" placeholder="City" required>
  <input type="text" name="dist" value="" placeholder="District" required>
  <input type="text" name="pin" value="" placeholder="Pin" required>
  <input type="text" name="state" value="" placeholder="State"  required>
-->

templates/base.html
{% load staticfiles %}




  <!-- Navigation -->
  {% block navigation %}
 
  {% include 'navbar.html' %}
 

  {% endblock %}
  
  {% block slider %}

  {% if request.path != '/' %}

  {% else %}
  {% include 'slider.html' %}

  {% endif %}

  
  
  {% endblock %}


  <!-- Page Content -->
 

    <!-- Jumbotron Header -->
    {% block mainblock %}

  

    {% endblock %}




    {% block sellernotifications %}
    {% endblock %}

    {% block createnotifications %}
    {% endblock %}

    {% block sellerorders %}
    {% endblock %}


  <!-- /.container -->



    <!-- footer area start -->
<center>
    <footer>
<hr>
      <!-- footer top area start -->
      <div class="footer-top pt-50 pb-50">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-12">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <div class="footer-logo mb-30">
                                  <a>
                                       <img src="{% static 'sinrato/assets/img/logo/logo-sinrato.png' %}" alt="">
                                  </a>
                              </div>
                          </div>

                      </div>
                  </div> <!-- single widget end -->
                   <!-- single widget end -->
                  <div class="col-lg-12 col-md-12 col-sm-12">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <h4>contact us</h4>
                          </div>
                          <div class="widget-body">
                              <div class="footer-useful-link">
                                  <ul>
                                      <li><span>Address:</span> Main Road, Hoshangabad 461001</li>
                                      <li><span>Email:</span><a href="mailto:kumar_yama@yahoo.co.in">kumar_yama@yahoo.co.in</a></li>
                                      <li><span>Call us:</span> <strong><a style="color: Black;" href="tel:+919827252649">+91 9827252649</a></strong></li>
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </div>

              </div>
          </div>
      </div>
      <!-- footer top area end -->
      <!-- footer bottom area start -->

      <div class="footer-bottom">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-12">
                      <div class="footer-bottom-content">
                          <div class="footer-copyright">
                              <center>
                          <p>Copyright © <span><script>document.write(new Date().getFullYear())</script></span> <a>kart Enterprises</a>. All Rights Reserved</p></center>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <!-- footer bottom area end -->
  </footer>
    </center>
  <!-- footer area end -->

  <!-- all js include here -->
  <script src="{% static 'sinrato/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/popper.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/plugins.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/ajax-mail.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/main.js' %}"></script>

</body>

</html>

templates/buyallproduct.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block mainblock %}

{% include 'customcss.html' %}




<div class="w3-container w3-padding">
  <h3>Review</h3>
  <div class="container">
    <form action="{% url 'buyer:buyallproduct' %} " method="post">
      {% csrf_token %}
      <label for="selone">Address</label> &nbsp;&nbsp;&nbsp; <a class="btn btn-primary" href="{% url 'buyer:addAddress' %}?next={{request.path}}">Add Address</a> <br><br>
      <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        {% for i in address %}
        <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
        {% endfor %}
      </select>
      <br><br><br>
      {% for i in obj %}
        <div class="w3-container w3-padding w3-border" >
          <p><b>{{ i.prodcartid.product_name }}</b></p>
          <img src="{{ i.prodcartid.product_img.url }}" alt="img" height="150" width="150">
          <br>
          <p>Description : {{ i.prodcartid.product_desc }}</p>
          <p>Stock : {{ i.prodcartid.product_avail }} items</p>
          <p>Price : {{ i.prodcartid.product_price }}</p>
          <p>Select Quantity</p>
          <select  name="selc" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </div>
        <input style="display:none;" type="number" name="ide" value="{{ i.id }}">
        <hr>
      {% endfor %}
      <p>Payment mode</p>
      <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        <option value="Online Wallet">Online Wallet</option>
        <option value="Cash on delivery">Cash on delivery</option>
      </select>
      <br>
      <br>
      <br>
      <input type="submit" name="sub" value="Reviewed" class="btn btn-warning">
      <br><br>
    </form>
  </div>
</div>
{% endblock %}

templates/customcss.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- CSS only -->
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}


.w3-border{
  border:1px solid yellow !important;
  border-radius: 5px;
}
</style>

templates/history.html
{% extends 'buyerside.html' %}


{% block history %}
<br>
<div class="w3-container">
  <div class="w3-container">
    <div class="w3-left">
      <form action="/buyer/order/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="order" value="Order History" class="w3-red" style="border:1px solid #CAFAFE;">
      </form>
    </div>
    <div class="w3-right">
      <form action="/buyer/notification/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" name="notify" value="Notifications" class="w3-red" style="border:1px solid #CAFAFE;">
      </form>
    </div>
  </div>
  <div class="w3-container">


    {% block order %}
    {% endblock %}

    {% block notification %}
    {% endblock %}
  </div>

</div>
<br>
{% endblock %}

templates/login_call.html
{% extends 'base.html' %}
{% block mainblock %}

<!-- Start of Login Wrapper -->
<div class="login-wrapper pb-70">
  <div class="container-fluid">
      <div class="row">
          <div class="col-12 col-sm-12 col-md-12 col-lg-12">
              <main id="primary" class="site-main">
                  <div class="user-login">
                      <div class="row">
                          <div class="col-12 col-sm-12 col-md-12">
                              <div class="section-title text-center">
                                  <h3>Log in to your account</h3>
                              </div>
                          </div>
                      </div> <!-- end of row -->
                      <div class="row">
                          <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-6 offset-lg-2 offset-xl-3">
                              <div class="login-form">
                                  <form method="post" class="form-group" enctype="multipart/form-data">
                                    {% csrf_token %} 
                                      <div class="form-group row align-items-center mb-4">
                                          <label for="email" class="col-12 col-sm-12 col-md-4 col-form-label">UserName</label>
                                          <div class="col-12 col-sm-12 col-md-8">
                                              <input type="text" class="form-control" id="email" name="usernm" value="" placeholder="Email" required>
                                          </div>
                                      </div>
                                      <div class="form-group row align-items-center mb-4">
                                          <label for="c-password" class="col-12 col-sm-12 col-md-4 col-form-label">Password</label>
                                          <div class="col-12 col-sm-12 col-md-8">
                                              <input type="password" class="form-control" id="c-password"  name="passwd" value="" placeholder="Password" required>
                                              <!-- <button class="pass-show-btn" type="button">Show</button> -->
                                          </div>
                                      </div>
                                      <div class="login-box mt-5 text-center">
                                          <p><a href="#">Forgot your password?</a></p>
                                          <button type="submit" class="btn btn-secondary mb-4 mt-4">Sign In</button>
                                      </div>
                                      <div class="text-center pt-20 top-bordered">
                                          <p>No account? <a href="{% url 'register' %}">Create one here</a>.</p>
                                      </div>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div> <!-- end of user-login -->
              </main> <!-- end of #primary -->
          </div>
      </div> <!-- end of row -->
  </div> <!-- end of container -->
</div>
<!-- End of Login Wrapper -->


{% endblock %}

templates/prodDeliveryDetails.html
{% extends 'buyerside.html' %}

{% block prodDeliveryDetail %}

<div class="jumbotron">
  
<h2><a href="{% url 'buyer:addAddress' %}?next={{request.path}}">Add Address</a>
</h2>
</div>


<div class="w3-container">
  <h3>Review</h3>
  <div class="w3-container">
    {{ product.product_name }}
    <br>
    <img src="{{ product.product_img.url }}" alt="img" height="130" width="150">
    <p>Description : {{ product.product_desc }}</p>
    <p>Items in stock : {{ product.product_avail }} items</p>
    <p>Retailer : {{ product.added_by_seller }}</p>
    <br>
  </div>

  
  <form  action="{% url 'buyer:addDeliveryDetails' id=idy %}" method="post">
    
    {% csrf_token %}
    <label for="selone">Address</label><br>
    {% if have_add %}
      <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        {% for i in address %}
        <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
        {% endfor %}
      </select>

    
    {% endif %}
   
   

    <br><br>
    <label for="seltwo">Quantaty</label><br>
    <select  name="sel" style="width:80%;border:2px solid orange;height:35px;" id="seltwo" required>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>
    <br><br>
    <label for="selthree">Payment Option</label><br>
    <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selthree" required>
      <option value="Online Wallet">Online Wallet</option>
      <option value="Cash on delivery">Cash on delivery</option>
    </select>
    <br>
    <br>
    <input type="submit" name="" value="Reviewed" class="w3-red w3-padding">
  </form>
</div>
<br>
{% endblock %}

templates/sinrato_showcart.html
{% extends 'base.html' %}

{% block mainblock %}

<div class="shopping-cart-wrapper pb-70">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <main id="primary" class="site-main">
                    <div class="shopping-cart">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="section-title">
                                    <h3>Shopping Cart</h3>
                                </div>

                                    <div class="table-responsive table-bordered">
                                        <table style="width: 100%;
  border-collapse: collapse;">
                                            <thead>
                                                <tr>
                                                    <td style=" font-weight: bold;padding: 10px">Image</td>
                                                    <td style=" font-weight: bold;padding: 10px">Product Name</td>
                                                   
                                                    <td></td>
                                                   
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for i in cart %}
                                                <tr>
                                                    <td style="padding: 10px">
                                                        <a><img src="{{ i.prodcartid.product_img.url }}" class="img-thumbnail"></a>
                                                    </td>

                                                    <td style="padding: 10px">
                                                        <a>{{ i.prodcartid.product_name }}</a><br>
                                                        <span style=" font-weight: bold;">Rs {{ i.prodcartid.product_price }}</span>
                                                       
                                                    </td>


                                                    <td style="padding: 10px">
                                                       


                                                    <form method="post"  action="{% url 'buyer:removecart' id=i.id %}">
                                                        {% csrf_token %}
                                                        <input type="submit" name="Remove" value="Remove" class="btn btn-danger" style="width:90px;">
                                                      </form>

                                                    </td>
                                              
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                             


                                <div class="cart-amount-wrapper">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-4 offset-md-8">
                                            <table class="table table-bordered">
                                                <tbody>
                                                    <tr>
                                                        <td>
                                                           
                                                            <a href="{% url 'buyer:buyallproduct' %}"><input type="submit" value="Buy all" name="All"  class="btn-1 home-btn" ></a>
             
                                                        </td>

                                                    </tr>
                                                    <tr>
                                                        <td><strong>Total:</strong></td>
                                                        <td><span class="color-primary">Rs {{ total }}</span></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <div class="cart-button-wrapper d-flex justify-content-between mt-4">
                                    <a href="{%  url 'buyer:buyerapp' %}" class="btn btn-secondary">Continue Shopping</a>
                                    <a href="{% url 'buyer:buyallproduct' %}" class="btn btn-secondary dark align-self-end">Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end of shopping-cart -->
                </main> <!-- end of #primary -->
            </div>
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div>

{% endblock %}

templates/viewproduct.html
{% extends 'buyerside.html' %}
{% load staticfiles %}

{% block viewproduct %}
<div class="w3-container">
  <a href="/buyer/buyerapp/"><button type="button" name="button" style="color:white;background-color:black;">Go back</button></a>
</div>
<br><br>
<div class="w3-display-container w3-container text-center">
  <img src="{{ pro.product_img.url }}" alt="Jeans" style="height: 5%;width:30%;">
  <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
  </div>
</div>
<div  class="w3-container w3-xlarge">
  <p style="background-color:black;color:#CAFAFE;" class="w3-left">Price : Rs {{ pro.product_price }} /- </p>
  <p style="background-color:black;color:#CAFAFE;margin-left:1%;" class="w3-left"> Offer : 50% Off</p>
</div>
<div class="w3-container w3-xlarge">
  {{ pro.product_name }}
  <p>Description : {{ pro.product_desc }}</p>
  <p>Items in stock : {{ pro.product_avail }} items</p>
  <p>Retailer : {{ pro.added_by_seller }}</p>
  <p>Payment Options : --------</p>
  <p>Delevery options : ---------</p>
  <br><br>
  <form method="post">
    {% csrf_token %}
    <a href="#"><input type="submit" name="" value="Add to My cart" style="color:#CAFAFE;background-color:black;border:2px solid #CAFAFE;"></a>
  </form>  
</div>
<br><br>
{% endblock %}